export const LOAD_TASKS = "LOAD_TASKS";

export const FETCH_TASKS_REQUEST = "FETCH_TASKS_REQUEST";
export const FETCH_TASKS_FAILURE = "FETCH_TASKS_FAILURE";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";

export const SHOW_UPDATE_ROW = "SHOW_UPDATE_ROW";
export const CHANGE_DESCRIPTION_TASK = "CHANGE_DESCRIPTION_TASK";
export const CHANGE_DEADLINE_TASK = "CHANGE_DEADLINE_TASK";
export const CANCEL_UPDATE_TASK = "CANCEL_UPDATE_TASK";

export const CHANGE_DROPDOWN = "CHANGE_DROPDOWN";

export const CHANGE_SEARCH = "CHANGE_SEARCH";




export const ADD_TASK = "ADD_TASK";
export const SHOW_DROPDOWN = "SHOW_DROPDOWN";
export const DELETE_TASK = "DELETE_TASK";
export const DELETE_SELECTED_TASKS = "DELETE_SELECTED_TASKS";
export const UPDATE_TASK = "UPDATE_TASK";
export const UPDATE_SELECTED_TASKS = "UPDATE_SELECTED_TASKS";
export const SELECT_TASK = "SELECT_TASK";
export const SELECT_ALL_TASKS = "SELECT_ALL_TASKS";
export const COMPLETE_TASK = "COMPLETE_TASK";
export const COMPLETE_SELECTED_TASKS = "COMPLETE_SELECTED_TASKS";
export const CHECK_TASKS_DEADLINE = "CHECK_TASKS_DEADLINE";
