export const CHANGE_SEARCH = "CHANGE_SEARCH";
export const NEW_TASK = "NEW_TASK";
export const CHANGE_DESCRIPTION = "CHANGE_DESCRIPTION";
export const CHANGE_DEADLINE = "CHANGE_DEADLINE";
export const CANCEL_UPDATE = "CANCEL_UPDATE";
export const ADD_TASK = "ADD_TASK";
export const SHOW_DROPDOWN = "SHOW_DROPDOWN";
export const DELETE_TASK = "DELETE_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const SELECT_TASK = "SELECT_TASK";
export const SELECT_ALL_TASK = "SELECT_ALL_TASK";

export const changeSearch = (value) => ({type: CHANGE_SEARCH, value: value});
export const newTask = () => ({type: NEW_TASK});
export const changeDescripton = (id ,value) => ({type: CHANGE_DESCRIPTION,id: id ,value: value});
export const changeDeadline = (id, direction) => ({type:CHANGE_DEADLINE,id: id, direction: direction});
export const cancelUpdate = id => ({type: CANCEL_UPDATE, id: id});
export const addTask = id => ({type: ADD_TASK, id: id});
export const showDropdown = id => ({type: SHOW_DROPDOWN, id: id});
export const deleteTask = id => ({type: DELETE_TASK, id: id});
export const updateTask = id => ({type: UPDATE_TASK, id: id});
export const selectTask = id => ({type: SELECT_TASK, id: id});
export const selectAllTask = () => ({type: SELECT_ALL_TASK});
